name: Add all new issues and PRs to the Automata board.

on:
  issues:
    types:
      - opened
      - transferred
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue/PR to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/orgs/woocommerce/projects/119
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
